services:
  - type: web
    name: mclub
    runtime: node
    plan: free
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./db/custom.db
      - key: PORT
        value: 3000
