#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Andy Japan Property ML V2 Report - V6 Parts 1/2/3 (Professional Chinese)
Framework from weixin-image.jpg, only sections 1, 2, 3.
Audience: Andy (investment novice)
Language: Professional Chinese (not Cantonese)
Summary formula: 房價變動 + 匯率變動 + 租金收入 - 稅費 - 銀行供款費用 (all HKD)
"""

import os, json, math

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm, mm
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image, KeepTogether, HRFlowable, CondPageBreak
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ═══════════════════════════════════════════════════
# FONTS
# ═══════════════════════════════════════════════════
pdfmetrics.registerFont(TTFont('NotoSerifSC', '/usr/share/fonts/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSCBold', '/usr/share/fonts/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('WenQuanYi', '/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc', subfontIndex=0))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSCBold')

# ═══════════════════════════════════════════════════
# COLOR PALETTE (auto-generated by pdf.py palette.generate)
# ═══════════════════════════════════════════════════
ACCENT = colors.HexColor('#4d2dac')
TEXT_PRIMARY = colors.HexColor('#1b1b19')
TEXT_MUTED = colors.HexColor('#7e7b72')
BG_SURFACE = colors.HexColor('#e7e6e2')
BG_PAGE = colors.HexColor('#f2f2ef')
SURFACE_RGBA = 'rgba(0,0,0,0.02)'

TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT = colors.white
TABLE_ROW_EVEN = colors.white
TABLE_ROW_ODD = BG_SURFACE

POSITIVE_COLOR = colors.HexColor('#1a6b3c')
NEGATIVE_COLOR = colors.HexColor('#9b2226')

# ═══════════════════════════════════════════════════
# STYLES
# ═══════════════════════════════════════════════════
W, H = A4
LM, RM, TM, BM = 2.2*cm, 2.2*cm, 2.5*cm, 2.5*cm
CW = W - LM - RM

def make_styles():
    s = {}
    s['h1'] = ParagraphStyle('H1', fontName='NotoSerifSC', fontSize=18, leading=26,
        textColor=TEXT_PRIMARY, spaceBefore=18, spaceAfter=10, alignment=TA_LEFT)
    s['h2'] = ParagraphStyle('H2', fontName='NotoSerifSC', fontSize=13, leading=20,
        textColor=ACCENT, spaceBefore=14, spaceAfter=8, alignment=TA_LEFT)
    s['h3'] = ParagraphStyle('H3', fontName='NotoSerifSC', fontSize=11.5, leading=17,
        textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=6, alignment=TA_LEFT)
    s['body'] = ParagraphStyle('Body', fontName='NotoSerifSC', fontSize=10.5, leading=18,
        textColor=TEXT_PRIMARY, spaceBefore=3, spaceAfter=6, alignment=TA_JUSTIFY, wordWrap='CJK')
    s['body_left'] = ParagraphStyle('BodyL', fontName='NotoSerifSC', fontSize=10.5, leading=18,
        textColor=TEXT_PRIMARY, spaceBefore=3, spaceAfter=6, alignment=TA_LEFT, wordWrap='CJK')
    s['caption'] = ParagraphStyle('Cap', fontName='NotoSerifSC', fontSize=9, leading=14,
        textColor=TEXT_MUTED, spaceBefore=4, spaceAfter=8, alignment=TA_CENTER, wordWrap='CJK')
    s['callout'] = ParagraphStyle('Callout', fontName='NotoSerifSC', fontSize=10.5, leading=17,
        textColor=ACCENT, spaceBefore=6, spaceAfter=6, alignment=TA_LEFT, wordWrap='CJK',
        leftIndent=12, borderColor=ACCENT, borderWidth=2, borderPadding=8)
    s['formula'] = ParagraphStyle('Formula', fontName='NotoSerifSC', fontSize=11, leading=18,
        textColor=TEXT_PRIMARY, spaceBefore=8, spaceAfter=8, alignment=TA_CENTER, wordWrap='CJK',
        backColor=colors.HexColor('#f0eff5'), borderPadding=10)
    s['small'] = ParagraphStyle('Small', fontName='NotoSerifSC', fontSize=9, leading=14,
        textColor=TEXT_MUTED, spaceBefore=2, spaceAfter=4, alignment=TA_LEFT, wordWrap='CJK')
    s['num'] = ParagraphStyle('Num', fontName='NotoSerifSCBold', fontSize=24, leading=32,
        textColor=ACCENT, spaceBefore=6, spaceAfter=4, alignment=TA_CENTER, wordWrap='CJK')
    return s

STY = make_styles()

# ═══════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════
def h1(t): return Paragraph(f'<b>{t}</b>', STY['h1'])
def h2(t): return Paragraph(f'<b>{t}</b>', STY['h2'])
def h3(t): return Paragraph(f'<b>{t}</b>', STY['h3'])
def p(t): return Paragraph(t, STY['body'])
def pl(t): return Paragraph(t, STY['body_left'])
def cap(t): return Paragraph(t, STY['caption'])
def callout(t): return Paragraph(t, STY['callout'])
def formula(t): return Paragraph(t, STY['formula'])
def small(t): return Paragraph(t, STY['small'])
def num(t): return Paragraph(t, STY['num'])

def fmt(val, prefix='HKD '):
    if val >= 0:
        return f'{prefix}+{val:.1f}万'
    else:
        return f'{prefix}{val:.1f}万'

def fmt_plain(val):
    if val >= 0:
        return f'+{val:.1f}万'
    else:
        return f'{val:.1f}万'

def make_table(headers, rows, col_widths=None):
    cw = col_widths or [CW / len(headers)] * len(headers)
    th = ParagraphStyle('TH', fontName='NotoSerifSC', fontSize=9.5, leading=14,
        textColor=TABLE_HEADER_TEXT, alignment=TA_CENTER, wordWrap='CJK')
    td = ParagraphStyle('TD', fontName='NotoSerifSC', fontSize=9.5, leading=14,
        textColor=TEXT_PRIMARY, alignment=TA_CENTER, wordWrap='CJK')
    tdl = ParagraphStyle('TDL', fontName='NotoSerifSC', fontSize=9.5, leading=14,
        textColor=TEXT_PRIMARY, alignment=TA_LEFT, wordWrap='CJK')
    data = [[Paragraph(h, th) for h in headers]]
    for row in rows:
        data.append([Paragraph(str(c), tdl if i == 0 else td) for i, c in enumerate(row)])
    t = Table(data, colWidths=cw, repeatRows=1, hAlign='CENTER')
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('TOPPADDING', (0, 0), (-1, 0), 8),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [TABLE_ROW_EVEN, TABLE_ROW_ODD]),
    ]))
    return t

def make_highlight_table(headers, rows, col_widths=None, highlight_last=True):
    """Table with optional highlighted last row."""
    cw = col_widths or [CW / len(headers)] * len(headers)
    th = ParagraphStyle('TH', fontName='NotoSerifSC', fontSize=9.5, leading=14,
        textColor=TABLE_HEADER_TEXT, alignment=TA_CENTER, wordWrap='CJK')
    td = ParagraphStyle('TD', fontName='NotoSerifSC', fontSize=9.5, leading=14,
        textColor=TEXT_PRIMARY, alignment=TA_CENTER, wordWrap='CJK')
    tdl = ParagraphStyle('TDL', fontName='NotoSerifSC', fontSize=9.5, leading=14,
        textColor=TEXT_PRIMARY, alignment=TA_LEFT, wordWrap='CJK')
    tdb = ParagraphStyle('TDB', fontName='NotoSerifSCBold', fontSize=10, leading=14,
        textColor=ACCENT, alignment=TA_CENTER, wordWrap='CJK')
    tdbl = ParagraphStyle('TDBL', fontName='NotoSerifSCBold', fontSize=10, leading=14,
        textColor=ACCENT, alignment=TA_LEFT, wordWrap='CJK')

    data = [[Paragraph(h, th) for h in headers]]
    for i, row in enumerate(rows):
        is_last = highlight_last and (i == len(rows) - 1)
        if is_last:
            data.append([Paragraph(str(c), tdbl if j == 0 else tdb) for j, c in enumerate(row)])
        else:
            data.append([Paragraph(str(c), tdl if j == 0 else td) for j, c in enumerate(row)])

    t = Table(data, colWidths=cw, hAlign='CENTER')
    cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc')),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]
    if highlight_last and len(rows) > 1:
        cmds.append(('ROWBACKGROUNDS', (0, 1), (-1, -2), [TABLE_ROW_EVEN, TABLE_ROW_ODD]))
        cmds.append(('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#e8e5f5')))
        cmds.append(('LINEABOVE', (0, -1), (-1, -1), 1.5, ACCENT))
    else:
        cmds.append(('ROWBACKGROUNDS', (0, 1), (-1, -1), [TABLE_ROW_EVEN, TABLE_ROW_ODD]))
    t.setStyle(TableStyle(cmds))
    return t

def color_val(val):
    """Return colored paragraph for positive/negative values."""
    if val > 0:
        s = ParagraphStyle('Pos', fontName='NotoSerifSC', fontSize=9.5, leading=14,
            textColor=POSITIVE_COLOR, alignment=TA_CENTER, wordWrap='CJK')
    elif val < 0:
        s = ParagraphStyle('Neg', fontName='NotoSerifSC', fontSize=9.5, leading=14,
            textColor=NEGATIVE_COLOR, alignment=TA_CENTER, wordWrap='CJK')
    else:
        s = ParagraphStyle('Zero', fontName='NotoSerifSC', fontSize=9.5, leading=14,
            textColor=TEXT_PRIMARY, alignment=TA_CENTER, wordWrap='CJK')
    return Paragraph(fmt_plain(val), s)


# ═══════════════════════════════════════════════════
# FINANCIAL PARAMETERS
# ═══════════════════════════════════════════════════
ENTRY_FX = 19.5          # JPY per HKD
PRICE_JPY = 62_400_000   # JPY
PRICE_HKD_WAN = 320.0    # HKD 万
EQUITY_HKD_WAN = 192.0   # HKD 万 (60%)
LOAN_JPY = 24_960_000    # JPY (40% LTV)
LOAN_HKD_WAN = 128.0     # HKD 万
RATE_ANNUAL = 0.03
MONTHLY_RATE = RATE_ANNUAL / 12
N_MONTHS_10 = 120

# Mortgage calculations
MP_JPY = LOAN_JPY * MONTHLY_RATE * (1 + MONTHLY_RATE)**N_MONTHS_10 / ((1 + MONTHLY_RATE)**N_MONTHS_10 - 1)
TOTAL_MORTGAGE_JPY = MP_JPY * N_MONTHS_10
TOTAL_INTEREST_JPY = TOTAL_MORTGAGE_JPY - LOAN_JPY
INTEREST_HKD_WAN = TOTAL_INTEREST_JPY / ENTRY_FX / 10000

# Rent calculations
ANNUAL_RENT_JPY = PRICE_JPY * 0.06       # JPY 374.4万
ANNUAL_COST_JPY = PRICE_JPY * 0.003      # JPY 18.7万 (property tax + management)
ANNUAL_NET_RENT_JPY = ANNUAL_RENT_JPY - ANNUAL_COST_JPY  # JPY 355.7万

# ML blended predictions for 10yr
FX_BLENDED_10 = 7.8   # JPY depreciation %
PR_BLENDED_10 = 5.0   # Property appreciation %

# 84 scenario parameters
FX_LEVELS = [13.0, 16.0, 19.5, 22.0, 24.0, 26.0, 28.0]
PR_ANNUAL_RATES = [-3.0, 0.0, 1.5, 3.0]
HOLDING_YEARS = [5, 7, 10]

def calc_full(fx_chg_pct, pr_chg_pct, years=10):
    """Calculate full return decomposition in HKD万."""
    exit_fx = ENTRY_FX * (1 + fx_chg_pct / 100)
    exit_jpy = PRICE_JPY * (1 + pr_chg_pct / 100)

    # Property gain: (exit_jpy - entry_jpy) / entry_fx, in HKD万
    prop_wan = (exit_jpy - PRICE_JPY) / ENTRY_FX / 10000

    # FX gain: price_jpy * (1/exit_fx - 1/entry_fx), in HKD万
    fx_wan = PRICE_JPY * (1 / exit_fx - 1 / ENTRY_FX) / 10000

    # Rent income (net of costs)
    total_net_rent_jpy = ANNUAL_NET_RENT_JPY * years
    rent_wan = total_net_rent_jpy / exit_fx / 10000

    # Tax/costs (already deducted from rent, but listed separately for clarity)
    total_tax_jpy = ANNUAL_COST_JPY * years
    tax_wan = total_tax_jpy / exit_fx / 10000

    # Interest (fixed cost in HKD)
    # Pro-rate for different holding periods
    if years == 10:
        interest_wan = INTEREST_HKD_WAN
    else:
        n_m = years * 12
        mp = LOAN_JPY * MONTHLY_RATE * (1 + MONTHLY_RATE)**n_m / ((1 + MONTHLY_RATE)**n_m - 1)
        total_mort = mp * n_m
        total_int_jpy = total_mort - LOAN_JPY
        interest_wan = total_int_jpy / ENTRY_FX / 10000

    net = prop_wan + fx_wan + rent_wan - tax_wan - interest_wan

    return {
        'exit_fx': exit_fx, 'exit_jpy': exit_jpy,
        'prop_wan': prop_wan, 'fx_wan': fx_wan,
        'rent_wan': rent_wan, 'tax_wan': tax_wan,
        'interest_wan': interest_wan, 'net_wan': net,
    }


# ═══════════════════════════════════════════════════
# GENERATE ALL 84 SCENARIOS
# ═══════════════════════════════════════════════════
all_scenarios = []
for fx in FX_LEVELS:
    fx_chg = (fx - ENTRY_FX) / ENTRY_FX * 100  # % change in FX rate
    for pr_annual in PR_ANNUAL_RATES:
        pr_total = ((1 + pr_annual / 100) ** 10 - 1) * 100  # total % over 10yr
        for yr in HOLDING_YEARS:
            # Scale property change proportionally for 5yr/7yr
            if yr == 10:
                pr_chg = pr_total
            elif yr == 7:
                pr_chg = ((1 + pr_annual / 100) ** 7 - 1) * 100
            else:
                pr_chg = ((1 + pr_annual / 100) ** 5 - 1) * 100

            # Scale FX change proportionally for 5yr/7yr
            if yr == 10:
                fx_chg_scaled = fx_chg
            elif yr == 7:
                fx_chg_scaled = fx_chg * 7 / 10
            else:
                fx_chg_scaled = fx_chg * 5 / 10

            r = calc_full(fx_chg_scaled, pr_chg, yr)
            r['fx_level'] = fx
            r['pr_annual'] = pr_annual
            r['years'] = yr
            r['fx_chg_pct'] = fx_chg_scaled
            r['pr_chg_pct'] = pr_chg
            all_scenarios.append(r)

# Key reference calculations
ml_10 = calc_full(FX_BLENDED_10, PR_BLENDED_10, 10)
best_10 = calc_full((13.0 - 19.5) / 19.5 * 100, (1.03**10 - 1) * 100, 10)
worst_10 = calc_full((28.0 - 19.5) / 19.5 * 100, ((0.97)**10 - 1) * 100, 10)


# ═══════════════════════════════════════════════════
# BUILD DOCUMENT
# ═══════════════════════════════════════════════════
OUT = '/home/z/my-project/download/andy_report_v6_p123_body.pdf'
CHART_DIR = '/home/z/my-project/download/ml_charts'

doc = SimpleDocTemplate(OUT, pagesize=A4,
    leftMargin=LM, rightMargin=RM, topMargin=TM, bottomMargin=BM)

story = []

# ═══════════════════════════════════════════════════════════════
# SECTION 1: 客戶入場決策
# ═══════════════════════════════════════════════════════════════
story.append(h1('一、客戶入場決策'))

story.append(h2('1.1 投資本金與入場條件'))

story.append(p('本報告針對客戶 Andy 擬投資之日本住宅物業進行全面評估。投資總額為港幣 320 萬元，按入場匯率 1 港元 = 19.5 日圓換算，折合日圓 6,240 萬元，用於購置日本住宅物業一處。資金結構方面，Andy 自付首期港幣 192 萬元（佔總價 60%），其餘港幣 128 萬元（佔總價 40%）通過銀行按揭貸款解決，貸款條件詳見下表。'))

# Entry conditions table
entry_rows = [
    ['物業總價', 'HKD 320 萬', 'JPY 6,240 萬'],
    ['自付首期', 'HKD 192 萬（60%）', '自籌資金'],
    ['銀行按揭', 'HKD 128 萬（40% LTV）', 'JPY 2,496 萬'],
    ['貸款利率', '年利率 3%', '10 年等額本息'],
    ['預期年租金回報率', '6%', 'JPY 374.4 萬 / 年'],
    ['入場匯率', '1 HKD = 19.5 JPY', '基準匯率'],
    ['買入交易成本', '物業價值 0.3%', '含各項手續費'],
]
story.append(make_table(['項目', '金額 / 比率', '備註'], entry_rows,
    col_widths=[CW*0.30, CW*0.35, CW*0.35]))
story.append(cap('表 1：投資入場條件一覽'))

story.append(h2('1.2 貸款條件與供款細節'))

story.append(p(f'銀行按揭貸款金額為日圓 2,496 萬元，年利率 3%，採用等額本息還款方式，貸款期限 10 年（120 個月）。經計算，每月供款為日圓 {MP_JPY:,.0f} 元，10 年供款總額為日圓 {TOTAL_MORTGAGE_JPY/10000:,.1f} 萬元，其中本金日圓 2,496 萬元，利息支出日圓 {TOTAL_INTEREST_JPY/10000:,.1f} 萬元（折合港幣約 {INTEREST_HKD_WAN:.1f} 萬元）。利息佔貸款本金的比例約為 {TOTAL_INTEREST_JPY/LOAN_JPY*100:.1f}%，屬於合理的融資成本範圍。'))

story.append(p('從現金流角度分析，物業預期年租金收入為日圓 374.4 萬元（6% 回報率），扣除每年持有成本（含物業稅、管理費等，約為物業價值 0.3%，即日圓 18.7 萬元）後，年淨租金收入為日圓 355.7 萬元。對比每年按揭供款日圓 289.2 萬元（月供 x 12），年淨租金收入足以覆蓋貸款供款，且每年盈餘約日圓 66.5 萬元。這意味着該投資在持有期間具備自給自足的現金流特徵，投資者無需額外貼補供款。'))

story.append(h2('1.3 核心問題'))

story.append(callout('核心問題：「投入 HKD 192 萬首期，10 年後我的投資會賺還是虧？」'))

story.append(p('這是 Andy 作為投資者最關心的根本問題。然而，任何負責任的回答都必須承認一個事實：沒有人能夠 100% 準確預測 10 年後的匯率和房價走勢。日本物業投資涉及兩個核心不確定因素——日圓匯率波動與日本住宅價格變動——兩者均受宏觀經濟、貨幣政策、地緣政治等多重因素影響，具有高度不確定性。'))

story.append(p('因此，本報告的目標並非給出一個確定性的「是」或「否」的答案，而是通過系統化的分析方法，將所有可能的未來情景進行量化計算，讓 Andy 能夠全面了解不同市場環境下的投資結果，從而做出知情決策。接下來的章節將逐步拆解影響投資回報的各項因素，並通過 84 種情景壓力測試呈現完整的風險回報圖譜。'))


# ═══════════════════════════════════════════════════════════════
# SECTION 2: 回報驅動因素拆解
# ═══════════════════════════════════════════════════════════════
story.append(h1('二、回報驅動因素拆解'))

story.append(p('要評估這筆投資的最終回報，首先需要理解哪些因素在驅動回報的變化。本章將所有影響投資盈虧的因素分為「確定因素」與「不確定因素」兩大類，並給出精確的計算公式。'))

story.append(h2('2.1 確定因素：可提前精確計算的項目'))

story.append(p('在投資的整個生命周期中，有兩項支出是可以在入場時就精確計算的，它們不隨市場波動而變化：'))

story.append(h3('（一）租金收入'))
story.append(p(f'物業預期年租金回報率為 6%，即每年可收到租金日圓 374.4 萬元。扣除每年持有成本（物業稅及管理費等合計日圓 18.7 萬元）後，年淨租金收入為日圓 355.7 萬元。如果持有 10 年，累計淨租金收入為日圓 3,557 萬元。需要強調的是，租金收入的最終港幣金額取決於 10 年後的日圓兌港元匯率——匯率不同，同樣的日圓租金折算成的港幣金額也會不同。因此，雖然日圓金額可以確定，但港幣金額仍存在匯率風險。'))

story.append(h3('（二）銀行供款費用（按揭利息）'))
story.append(p(f'這是一項完全確定的成本。無論市場如何波動，Andy 都需要按月向銀行償還貸款。10 年貸款期內，利息總額為日圓 396.2 萬元。由於利息支出在貸款起始時已經確定（固定利率），且按揭供款以日圓為單位，我們可以將其按入場匯率直接折算為港幣約 {INTEREST_HKD_WAN:.1f} 萬元。這筆支出是投資的「硬成本」，不受任何市場因素影響。'))

story.append(h2('2.2 不確定因素：決定最終盈虧的關鍵'))

story.append(p('與確定因素相對，以下兩項因素是無法在入場時精確預知的，它們將決定這筆投資的最終盈虧：'))

story.append(h3('（一）匯率變化（JPY/HKD）'))
story.append(p('Andy 以港元購買日本物業，本金的投入和回收涉及兩次貨幣兌換：入場時將港元換為日圓購買物業，退出時將出售物業所得的日圓換回港元。入場匯率為 1 港元 = 19.5 日圓已經確定，但 10 年後的退出匯率完全未知。'))

story.append(p('匯率變動對投資回報的影響可以這樣理解：如果 10 年後日圓貶值（例如 1 港元 = 21 日圓），意味着同樣數額的日圓資產換回的港元變少了，投資者會因此蒙受匯率損失。反之，如果日圓升值（例如 1 港元 = 16 日圓），同樣的日圓資產換回更多港元，投資者將獲得額外的匯率收益。匯率波動的幅度可能非常顯著——歷史上日圓兌港元匯率曾在 10 至 25 之間大幅波動，這使得匯率成為海外物業投資中最大的風險因素。'))

story.append(h3('（二）物業價格變幅'))
story.append(p('日本住宅物業的價格在未來 10 年是漲還是跌，以及漲跌幅度多大，是另一個核心不確定因素。物業價格受日本國內經濟狀況、人口結構變化、貨幣政策、土地供給等多重因素影響。歷史上，日本樓價經歷過 1990 年代泡沫破裂後的長期下跌，也經歷過近年來的復甦上升。物業價格的變動直接影響 10 年後出售物業時能收回的日圓金額。'))

story.append(h2('2.3 核心計算公式'))

story.append(p('綜合以上分析，投資的最終盈虧可以拆解為五個獨立項目，每個項目均以港幣（HKD）萬元為單位。這五個項目分別對應上述的確定因素和不確定因素：'))

story.append(formula('<b>投資淨回報 = 房價變動 + 匯率變動 + 租金收入 - 稅費 - 銀行供款費用</b>'))

story.append(p('以下對公式中各項進行精確定義：'))

story.append(pl('<b>房價變動</b> =（10 年後物業日圓價值 - 入場日圓價值） / 入場匯率'))
story.append(pl('  反映日本物業本身價格的升跌，以港幣計量。'))
story.append(Spacer(1, 4))
story.append(pl('<b>匯率變動</b> = 物業日圓價值 x（1/退出匯率 - 1/入場匯率）'))
story.append(pl('  反映匯率波動對資產港幣價值的影響。即使物業日圓價格不變，匯率變動單獨就會造成港幣盈虧。'))
story.append(Spacer(1, 4))
story.append(pl('<b>租金收入</b> = 10 年累計淨租金（日圓）/ 退出匯率'))
story.append(pl('  每年租金扣除管理費和物業稅後的淨收入，按退出匯率折算為港幣。'))
story.append(Spacer(1, 4))
story.append(pl('<b>稅費</b> = 10 年累計持有成本（日圓）/ 退出匯率'))
story.append(pl('  包含物業稅、管理費等，已在租金中扣減，此處單獨列出以清晰展示。'))
story.append(Spacer(1, 4))
story.append(pl('<b>銀行供款費用</b> = 10 年按揭利息總額（港幣）'))
story.append(pl('  固定成本，按入場匯率折算，不受匯率波動影響。'))

story.append(Spacer(1, 6))
story.append(p('這個公式的核心邏輯是：投資者的最終盈虧等於「賺到的錢」（房價升值 + 匯率收益 + 租金收入）減去「花出去的錢」（稅費 + 利息）。其中，房價變動和匯率變動是不確定的，租金收入和銀行利息是相對確定的，稅費金額較小且可預測。'))


# ═══════════════════════════════════════════════════════════════
# SECTION 3: 84 情景壓力測試
# ═══════════════════════════════════════════════════════════════
story.append(h1('三、84 情景壓力測試'))

story.append(p('第二章已經拆解了影響投資回報的各項因素，並給出了核心計算公式。本章將該公式應用於一組系統化的情景矩陣中，通過遍歷所有合理的匯率和房價組合，全面展示不同市場環境下的投資結果。'))

story.append(h2('3.1 情景矩陣設計'))

story.append(p('情景矩陣由三個維度構成，每個維度設定多個等級，三個維度的全排列組合共產生 84 個獨立情景。這種方法確保了分析的全面性——無論未來市場走勢如何，只要不超出設定的參數範圍，其投資結果都已在 84 個情景中得到覆蓋。'))

# Scenario matrix table
matrix_rows = [
    ['匯率（JPY/HKD）', '7 級', '13.0 / 16.0 / 19.5 / 22.0 / 24.0 / 26.0 / 28.0',
     '覆蓋日圓大幅升值至大幅貶值的完整區間'],
    ['樓價年變幅', '4 級', '-3% / 0% / +1.5% / +3%',
     '涵蓋持續下跌至穩健增長的合理範圍'],
    ['持有年期', '3 級', '5 年 / 7 年 / 10 年',
     '對應短中長三種投資週期'],
    ['情景總數', '84 個', '7 x 4 x 3 = 84',
     '每個情景均使用核心公式精確計算'],
]
story.append(make_table(['維度', '等級數', '設定值', '設計邏輯'], matrix_rows,
    col_widths=[CW*0.18, CW*0.10, CW*0.38, CW*0.34]))
story.append(cap('表 2：84 情景壓力測試矩陣設計'))

story.append(p('匯率範圍的設定依據如下：入場匯率 19.5 JPY/HKD 作為中間值，向上延伸至 13.0（日圓大幅升值約 33%）和向下至 28.0（日圓大幅貶值約 44%）。這一範圍覆蓋了過去數十年日圓匯率的歷史波動區間，具有充分的參考價值。樓價年變幅從 -3%（持續下跌）到 +3%（穩健增長），涵蓋了日本房地產市場在不同經濟週期中的典型表現。'))

story.append(h2('3.2 核心情景計算示例'))

story.append(p('為了讓 Andy 直觀理解計算邏輯，以下以三個最具代表性的情景為例，展示核心公式的完整計算過程。每個情景均給出五項回報分解，最終得出該情景下的投資淨回報。'))

# --- ML Blended 10yr scenario ---
story.append(h3('情景 A：模型預測情景（最可能情景）'))

story.append(p(f'此情景採用機器學習模型對未來 10 年匯率和房價的預測值作為輸入。模型預測日圓 10 年累計貶值約 7.8%（退出匯率約 21.0 JPY/HKD），日本住宅價格 10 年累計上升約 5.0%。這是基於數十年歷史數據訓練得出的最可能結果。'))

story.append(make_highlight_table(
    ['項目', '金額（HKD）', '說明'],
    [
        ['房價變動', fmt_plain(ml_10['prop_wan']), '樓價升 5.0%，資產增值'],
        ['匯率變動', fmt_plain(ml_10['fx_wan']), '日圓貶 7.8%，匯率損失'],
        ['租金收入', fmt_plain(ml_10['rent_wan']), '10 年淨租金按退出匯率折算'],
        ['稅費', fmt_plain(-ml_10['tax_wan']), '10 年持有成本'],
        ['銀行供款費用', fmt_plain(-ml_10['interest_wan']), '10 年按揭利息'],
        ['投資淨回報', fmt_plain(ml_10['net_wan']), f'首期 192 萬 → 約 HKD {EQUITY_HKD_WAN + ml_10["net_wan"]:.1f} 萬'],
    ],
    col_widths=[CW*0.22, CW*0.22, CW*0.56]
))
story.append(cap('表 3：情景 A（模型預測）投資回報分解'))

# --- Best scenario ---
story.append(h3('情景 B：最樂觀情景（日圓升值 + 樓價上升）'))

story.append(p(f'此情景假設日圓大幅升值至 13.0 JPY/HKD（較入場匯率升值約 33%），同時日本樓價每年上升 3%。這代表最為有利的市場環境：日圓升值使資產換回更多港元，樓價上升使資產本身增值，兩者疊加產生最大的投資回報。'))

story.append(make_highlight_table(
    ['項目', '金額（HKD）', '說明'],
    [
        ['房價變動', fmt_plain(best_10['prop_wan']), '樓價年升 3%，10 年累計大幅增長'],
        ['匯率變動', fmt_plain(best_10['fx_wan']), '日圓大幅升值，匯率收益顯著'],
        ['租金收入', fmt_plain(best_10['rent_wan']), '日圓強勢，租金折算港元更多'],
        ['稅費', fmt_plain(-best_10['tax_wan']), '10 年持有成本'],
        ['銀行供款費用', fmt_plain(-best_10['interest_wan']), '10 年按揭利息'],
        ['投資淨回報', fmt_plain(best_10['net_wan']), f'首期 192 萬 → 約 HKD {EQUITY_HKD_WAN + best_10["net_wan"]:.1f} 萬'],
    ],
    col_widths=[CW*0.22, CW*0.22, CW*0.56]
))
story.append(cap('表 4：情景 B（最樂觀）投資回報分解'))

# --- Worst scenario ---
story.append(h3('情景 C：最悲觀情景（日圓貶值 + 樓價下跌）'))

story.append(p(f'此情景假設日圓大幅貶值至 28.0 JPY/HKD（較入場匯率貶值約 44%），同時日本樓價每年下跌 3%。這代表最為不利的市場環境：日圓貶值使資產換回更少港元，樓價下跌使資產本身縮水，雙重打擊下投資回報大幅下降。'))

story.append(make_highlight_table(
    ['項目', '金額（HKD）', '說明'],
    [
        ['房價變動', fmt_plain(worst_10['prop_wan']), '樓價年跌 3%，10 年累計大幅縮水'],
        ['匯率變動', fmt_plain(worst_10['fx_wan']), '日圓大幅貶值，匯率損失嚴重'],
        ['租金收入', fmt_plain(worst_10['rent_wan']), '日圓疲弱，租金折算港元減少'],
        ['稅費', fmt_plain(-worst_10['tax_wan']), '10 年持有成本'],
        ['銀行供款費用', fmt_plain(-worst_10['interest_wan']), '10 年按揭利息'],
        ['投資淨回報', fmt_plain(worst_10['net_wan']), f'首期 192 萬 → 約 HKD {EQUITY_HKD_WAN + worst_10["net_wan"]:.1f} 萬'],
    ],
    col_widths=[CW*0.22, CW*0.22, CW*0.56]
))
story.append(cap('表 5：情景 C（最悲觀）投資回報分解'))

story.append(h2('3.3 三情景對照總覽'))

story.append(p('下表將三個代表性情景的五項回報並列對照，清晰呈現不同市場環境對各項回報的差異化影響。通過對比可以發現，租金收入在所有情景下均為最大的正數項目，是該投資的核心利潤來源；而匯率變動則是波動最大的項目，直接決定了投資回報的上限和下限。'))

# Comparison table with colored values
comp_headers = ['回報項目', '情景 A（模型預測）', '情景 B（最樂觀）', '情景 C（最悲觀）']
comp_rows = [
    ['房價變動', ml_10['prop_wan'], best_10['prop_wan'], worst_10['prop_wan']],
    ['匯率變動', ml_10['fx_wan'], best_10['fx_wan'], worst_10['fx_wan']],
    ['租金收入', ml_10['rent_wan'], best_10['rent_wan'], worst_10['rent_wan']],
    ['稅費', -ml_10['tax_wan'], -best_10['tax_wan'], -worst_10['tax_wan']],
    ['銀行供款費用', -ml_10['interest_wan'], -best_10['interest_wan'], -worst_10['interest_wan']],
    ['投資淨回報', ml_10['net_wan'], best_10['net_wan'], worst_10['net_wan']],
]

th_s = ParagraphStyle('THC', fontName='NotoSerifSC', fontSize=9, leading=13,
    textColor=TABLE_HEADER_TEXT, alignment=TA_CENTER, wordWrap='CJK')
tdl_s = ParagraphStyle('TDLC', fontName='NotoSerifSC', fontSize=9, leading=13,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, wordWrap='CJK')
tdb_s = ParagraphStyle('TDBC', fontName='NotoSerifSCBold', fontSize=9.5, leading=13,
    textColor=ACCENT, alignment=TA_CENTER, wordWrap='CJK')
tdbl_s = ParagraphStyle('TDBLC', fontName='NotoSerifSCBold', fontSize=9.5, leading=13,
    textColor=ACCENT, alignment=TA_LEFT, wordWrap='CJK')

comp_data = [[Paragraph(h, th_s) for h in comp_headers]]
for i, row in enumerate(comp_rows):
    is_last = (i == len(comp_rows) - 1)
    label_cell = Paragraph(row[0], tdbl_s if is_last else tdl_s)
    val_cells = []
    for val in row[1:]:
        if is_last:
            val_cells.append(Paragraph(fmt_plain(val), tdb_s))
        else:
            val_cells.append(color_val(val))
    comp_data.append([label_cell] + val_cells)

t_comp = Table(comp_data, colWidths=[CW*0.24, CW*0.25, CW*0.25, CW*0.26], hAlign='CENTER')
t_comp.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
    ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc')),
    ('ROWBACKGROUNDS', (0, 1), (-1, -2), [TABLE_ROW_EVEN, TABLE_ROW_ODD]),
    ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#e8e5f5')),
    ('LINEABOVE', (0, -1), (-1, -1), 1.5, ACCENT),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
    ('TOPPADDING', (0, 0), (-1, -1), 7),
    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
]))
story.append(t_comp)
story.append(cap('表 6：三種代表性情景投資回報對照（HKD 萬元）'))


story.append(h2('3.4 84 情景完整計算結果'))

story.append(p('以下表格展示 84 個情景的完整計算結果。表格按持有年期分組（10 年 / 7 年 / 5 年），每組內按匯率等級和樓價年變幅排列。每個情景均使用第二章的核心公式進行精確計算，五項回報之和即為該情景下的投資淨回報。正數表示盈利，負數表示虧損。'))

# Generate 84 scenario tables by holding period
for yr in [10, 7, 5]:
    yr_label = f'{yr} 年持有'
    story.append(h3(f'持有 {yr} 年情景一覽'))

    yr_scenarios = [s for s in all_scenarios if s['years'] == yr]

    # Table headers
    s84_th = ParagraphStyle('S84TH', fontName='NotoSerifSC', fontSize=8, leading=11,
        textColor=TABLE_HEADER_TEXT, alignment=TA_CENTER, wordWrap='CJK')
    s84_td = ParagraphStyle('S84TD', fontName='NotoSerifSC', fontSize=8, leading=11,
        textColor=TEXT_PRIMARY, alignment=TA_CENTER, wordWrap='CJK')
    s84_tdl = ParagraphStyle('S84TDL', fontName='NotoSerifSC', fontSize=8, leading=11,
        textColor=TEXT_PRIMARY, alignment=TA_LEFT, wordWrap='CJK')
    s84_tdb = ParagraphStyle('S84TDB', fontName='NotoSerifSCBold', fontSize=8.5, leading=11,
        textColor=ACCENT, alignment=TA_CENTER, wordWrap='CJK')

    headers_84 = ['匯率\n(JPY/HKD)', '樓價年變幅', '房價變動', '匯率變動', '租金收入', '稅費', '利息', '淨回報\n(HKD萬)']
    col_w_84 = [CW*0.11, CW*0.11, CW*0.12, CW*0.12, CW*0.13, CW*0.10, CW*0.10, CW*0.12]

    data_84 = [[Paragraph(h.replace('\n', '<br/>'), s84_th) for h in headers_84]]

    for s in yr_scenarios:
        row = [
            Paragraph(f'{s["fx_level"]:.1f}', s84_td),
            Paragraph(f'{s["pr_annual"]:+.1f}%', s84_td),
            Paragraph(fmt_plain(s['prop_wan']), s84_td),
            Paragraph(fmt_plain(s['fx_wan']), s84_td),
            Paragraph(fmt_plain(s['rent_wan']), s84_td),
            Paragraph(fmt_plain(-s['tax_wan']), s84_td),
            Paragraph(fmt_plain(-s['interest_wan']), s84_td),
            Paragraph(f'<b>{fmt_plain(s["net_wan"])}</b>', s84_tdb),
        ]
        data_84.append(row)

    t_84 = Table(data_84, colWidths=col_w_84, repeatRows=1, hAlign='CENTER')
    cmds_84 = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#dddddd')),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [TABLE_ROW_EVEN, TABLE_ROW_ODD]),
        ('LINEABOVE', (0, -1), (-1, -1), 0.8, ACCENT),
    ]
    t_84.setStyle(TableStyle(cmds_84))
    story.append(t_84)
    story.append(cap(f'表：84 情景壓力測試 — 持有 {yr} 年全部 {len(yr_scenarios)} 個情景（HKD 萬元）'))
    story.append(Spacer(1, 6))


story.append(h2('3.5 情景分析關鍵發現'))

story.append(p('通過對 84 個情景的系統化計算，可以得出以下幾個關鍵結論：'))

story.append(p('<b>第一，租金收入是投資回報的核心支柱。</b>在全部 84 個情景中，租金收入始終是最大的正數項目，其金額遠超房價變動和匯率變動的影響。即使在最悲觀的情景下（日圓貶值至 28.0 + 樓價年跌 3%），10 年租金收入仍能提供可觀的現金流入，有效緩衝資產價值下跌和匯率損失的衝擊。這意味着該投資的回報結構以租金驅動為主，而非依賴資產升值。'))

story.append(p('<b>第二，匯率是最大的不確定因素。</b>對比同樣的樓價變幅下不同匯率的情景，匯率變動對最終回報的影響幅度遠大於房價變動。例如在樓價不變（0% 年變幅）、持有 10 年的條件下，匯率從 13.0 到 28.0 的變動可使淨回報相差超過 300 萬港元。這印證了海外物業投資中匯率風險的核心地位。'))

story.append(p('<b>第三，多數情景下投資為正回報。</b>在 10 年持有的 28 個情景中，絕大多數情景的投資淨回報為正數。只有在極端悲觀條件（匯率大幅貶值 + 樓價持續下跌）的組合下，才出現負回報。即使是這些負回報情景，虧損幅度也相對有限，主要得益於租金收入的持續補充。'))

story.append(p('<b>第四，持有期越長，租金的累積效應越顯著。</b>對比 5 年、7 年和 10 年的情景結果，可以明確看到隨著持有期延長，累計租金收入大幅增長，使得投資的整體回報水平提升，同時也增強了抗風險能力。這意味着如果 Andy 的資金週期允許，較長的持有期對該投資更为有利。'))

story.append(callout('綜上所述，84 情景壓力測試的結果表明：在絕大多數合理的市場情景下，該日本物業投資能夠產生正的淨回報。最大的風險來自日圓匯率的大幅貶值，但租金收入的規模足以在大部分情景下覆蓋這一風險。後續章節將引入機器學習模型，進一步評估每個情景發生的實際機率。'))


# ═══════════════════════════════════════════════════
# BUILD PDF
# ═══════════════════════════════════════════════════
doc.build(story)
print(f'V6 Parts 1/2/3 Body PDF generated: {OUT}')
print(f'Pages: ~8-10')
print(f'ML 10yr net: HKD {ml_10["net_wan"]:.1f}万')
print(f'Best 10yr net: HKD {best_10["net_wan"]:.1f}万')
print(f'Worst 10yr net: HKD {worst_10["net_wan"]:.1f}万')